export const examData = [
  {
    examName: "یازدهمین آزمون مشترک دستگاه های اجرایی",
    exams: [
      {
        id: 1,
        category: "آزمون کتبی",
        date: "۱۴۰۲/۱۱/۱۵",
        status: "برگزار شده",
        score: "۷۴",
        percentage: "۸۵%",
        candidateStatus: "قبول شده",
      },
      {
        id: 2,
        category: "ارزیابی تکمیلی",
        date: "۱۴۰۲/۱۲/۰۲",
        status: "برگزار شده",
        score: "غایب",
        percentage: "۰",
        candidateStatus: "غایب",
      },
      {
        id: 3,
        category: "گزینش",
        date: "۱۴۰۲/۱۲/۰۲",
        status: "در حال برگزاری",
        score: "نامشخص",
        percentage: "نامشخص",
        candidateStatus: "نامشخص",
      },
    ],
  },
  {
    examName: "آزمون استخدامی سازمان اداری و استخدامی کشور",
    exams: [
      {
        id: 4,
        category: "آزمون کتبی",
        date: "۱۴۰۳/۰۱/۱۰",
        status: "برگزار شده",
        score: "۴۰",
        percentage: "۴۵%",
        candidateStatus: "مردود",
      },
      {
        id: 5,
        category: "ارزیابی تکمیلی",
        date: "۱۴۰۳/۰۱/۱۵",
        status: "در انتظار اعلام نتایج",
        score: "نامشخص",
        percentage: "نامشخص",
        candidateStatus: "نامشخص",
      },
      {
        id: 6,
        category: "گزینش",
        date: "۱۴۰۳/۰۱/۲۰",
        status: "در حال برگزاری",
        score: "نامشخص",
        percentage: "نامشخص",
        candidateStatus: "نامشخص",
      },
    ],
  },
];
