export const examData = [
  {
    examName: "آزمون پنجم",
    exams: [
      {
        id: 1,
        category: "آزمون کتبی",
        date: "۱۴۰۲/۱۱/۱۵",
        status: "برگزار شده",
        score: "۷۴",
        percentage: "۸۵%",
        candidateStatus: "قبول شده",
      },
      {
        id: 2,
        category: "ارزیابی تکمیلی",
        date: "۱۴۰۲/۱۲/۰۲",
        status: "در انتظار اعلام نتایج",
        score: "۲۴",
        percentage: "۳۰%",
        candidateStatus: "مردود",
      },
      {
        id: 3,
        category: "گزینش",
        date: "۱۴۰۲/۱۲/۰۲",
        status: "در حال برگزاری",
        score: "۰",
        percentage: "-",
        candidateStatus: "غایب",
      },
    ],
  },
  {
    examName: "آزمون دوازدهم",
    exams: [
      {
        id: 4,
        category: "آزمون کتبی",
        date: "۱۴۰۳/۰۱/۱۰",
        status: "برگزار شده",
        score: "۶۰",
        percentage: "۷۵%",
        candidateStatus: "قبول شده",
      },
      {
        id: 5,
        category: "ارزیابی تکمیلی",
        date: "۱۴۰۳/۰۱/۱۵",
        status: "در انتظار اعلام نتایج",
        score: "۴۰",
        percentage: "۴۰%",
        candidateStatus: "مردود",
      },
      {
        id: 6,
        category: "گزینش",
        date: "۱۴۰۳/۰۱/۲۰",
        status: "در حال برگزاری",
        score: "۰",
        percentage: "-",
        candidateStatus: "غایب",
      },
    ],
  },
];
